deployment/sklearn/sklearn-census-end-to-end.ipynb

See PR comments for pain points addressed.
Low risk: It's fundamentally the same code.
Low AoE: Self-contained.
Ran it 3 times to be sure it works.
Revert this PR.

docs: Update census notebook so it's friendlier to use

---

monitoring/Monitoring-census-example.ipynb

Add monitoring census example

---

deployment/external-scan/build_MV_and_fetch_image.py

The user provides a MV. This script creates a build for the MV and returns the image location once the build is complete. Also, if the user wants this build to be scanned externally, this script will mark the build as such.

feat: [VRD-262] Script to create build and fetch image for MV

---

deployment/external-scan/build_MV_and_fetch_image.py
deployment/external-scan/save_external_scan_results.py

feat: [VRD-262] Script to save external scan results to dep-api

---

deployment/promotion/promote.py

- Adds the prototype promotion script

Promotion script prototype

---

deployment/promotion/promote.py

- Adds logging around artifact upload failure

Error handling around artifact upload

---

deployment/promotion/promote.py

- Adds external build location field to build

Add build external location to promotion script

---

deployment/promotion/promote.py

Still in progress! So far have added some checks in the case that there are no labels and I've separated the destination endpoint path from the source path.

chore: [VRD-336] Clean up promotion script

---

monitoring/Monitoring-housing-regression-example.ipynb

Add regression example for monitoring

---

deployment/promotion/promote.py

The source workspace was being used instead of destination workspace, in dest config

fix: use dest workspace env var

---

deployment/promotion/create_scb.py
deployment/promotion/promote.py

This PR changes the Promotion script to directly promoting a specific build of a model version, as opposed to promoting an endpoint and its associated build.
- Environment variable configuration has changed:
- VERTA_SOURCE_MODEL_VERSION_ID added as the configuration parameter to specify the source of promotion
- VERTA_SOURCE_ENDPOINT_PATH removed
- VERTA_DEST_ENDPOINT_PATH removed
- Fixed duplicate upload of `model.pkl` artifact
- Find the latest self contained build of the promoted model version
- Warn and exit if no candidate builds are found
- Added a stub function `upload_build` which can be used as an extension point to add custom upload behavior for S3 artifacts. Input to the function is a dict which contains an S3 path in the `location` key. The output of this function must be the …

VRD-386 Promote self contained builds

---

deployment/external-scan/save_external_scan_results.py

Update script to match updated API input, now that `scan_external_results` is strictly typed to:
```
{
"url": "urltoscanresult.com",
"safety_status": "safe"
}
```
Low risk, this is a script run on-demand.
Ran the script!

feat: [VRD-430] Update script to accept url and safety status

---

deployment/promotion/promote.py

This script allows the user to choose whether to promote to an existing registered model or create a new one, based on the provided environment variables.
I used the script to promote to a new RM and an existing RM.

feat: [VRD-426] Allow promotion to existing registered model

---

deployment/h2o/h2o-deployment.ipynb

Add h2o example notebook

---

deployment/h2o/h2o-deployment.ipynb

We learned some things while integrating h2o into our CI test suite. Adding these learnings to this example notebook.
Successfully ran the notebook!

Update h2o example model

---

deployment/h2o/h2o-deployment.ipynb

chore: Fix confusing comment

---

deployment/promotion/promote.py

- Updates promoted build message to the message from the source build.
- Uses creator request flags from the source build when creating promoted build.
AoE: Build creation
Risk: Low
- Personal env
- dev
- testsqlserver

VRD-521: propagate build message and creator flags in promotion

---

deployment/promotion/promote.py

This change will copy over descriptions for the RM and RMV and the labels for the RMV (they're already being copied for RM).
This will also allow the user to copy over a RMV that was created from an ER (although it does not yet copy over all the underlying ER data at this time).
Ran the script!

feat: [VRD-523] Copy additional RMV metadata

---

deployment/nltk-sklearn/spam-detection.ipynb

Apparently this is now required for the notebook's model
—
I ran the notebook to completion in Colab: https://colab.research.google.com/github/VertaAI/examples/blob/liu/nltk/deployment/nltk-sklearn/spam-detection.ipynb
I also searched the repo for other uses of NLTK, and this appears to be the only one
Revert this PR.

docs: Fix NLTK notebook

---

monitoring/Monitoring-batch-reference-data-example.ipynb
monitoring/Monitoring-census-example.ipynb
monitoring/Monitoring-isOdd-example.ipynb

Adds a new example notebook to the monitoring directory, which provides a working example of batch reference data ingestion and produces meaningful data in the charts and graphs for monitoring drift etc.
Does not affect production code.  The example notebook has been validated in several environments.

feature: [VMM-584] New monitoring notebook with batch reference data example

---

deployment/sklearn/sklearn-census-income-prediction.ipynb

Add example notebook using scikit-learning with LabelEncoder (handling categorical variables).

docs: Add LabelEncoder example

---

deployment/huggingface/yolos-seq2seq.ipynb

Hugging Face example

---

deployment/huggingface/yolos-seq2seq.ipynb
deployment/lightgbm/lightgbm-house-price-prediction.ipynb
deployment/pytorch/torch-hub-yolov5.ipynb
deployment/sklearn/sklearn-census-income-prediction.ipynb
deployment/sklearn/sklearn-gbm-house-price-prediction.ipynb
deployment/sklearn/sklearn-housing-regression-gbr.ipynb
deployment/tfhub/object-detection-base64.ipynb
deployment/tfhub/object-detection-url.ipynb

Code patterns for developed NBs.

NBs code patterns

---

deployment/promotion/promote.py

- Fixes an issue that would allow the promotion script to promote non self contained builds

only promote self contained builds

---

deployment/export-to-spark/insurance-xsell-prediction-batch-prediction.ipynb

New example in the `deployment` directory.
Low risk

docs: Export to Spark Example

---

registry/import_models_to_verta/mlflow_databricks_bulk_import_example.ipynb

see thread here: https://vertaai.slack.com/archives/C05L3DK08ER/p1693584648579409

update to use mlflow version

---

registry/import_models_to_verta/mlflow_databricks_bulk_import_example.ipynb

remove print
